name: Trigger-All-Workflows

on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * 5"

permissions:
  contents: write
  actions: write

jobs:

    zn-m2-oc:
      uses: ./.github/workflows/zn-m2-oc.yml

    zn-m2-pw:
      uses: ./.github/workflows/zn-m2-pw.yml
